# Generated by Django 3.1.4 on 2021-01-11 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SuperBikes', '0002_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
