# Generated by Django 3.1.4 on 2021-01-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperBikes', '0005_carbrands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbrands',
            old_name='img_address',
            new_name='brand_name',
        ),
    ]
