# Generated by Django 3.1.4 on 2021-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperBikes', '0006_auto_20210127_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
